approved = [
    "mit",
    "apache-2.0",
    "bsd-3-clause",
    "bsd-2-clause",
    "mpl-2.0",
]

ignored = [
  "github.com/ghodss/yaml",
  "github.com/gogo/protobuf",
  "sigs.k8s.io/yaml",
  "github.com/davecgh/go-spew", # ISC license

  "go.uber.org/atomic",
  "go.uber.org/multierr",
  "emperror.dev/errors",
]
